- name: close swap
  shell: |
    swapoff -a
    sed -i '/ swap /s/.*/#&/g' /etc/fstab

- name: copy network config
  copy:
    src: k8s.conf
    dest: /etc/sysctl.d/k8s.conf


- name: config network
  shell: sysctl --system

- name: copy k8s repo
  copy:
    src: kubernetes.repo
    dest: /etc/yum.repos.d/kubernetes.repo

- name: install k8s components
  yum:
    name: 
      - kubectl
      - kubelet
      - kubeadm
      - wget
    state: present
    disable_gpg_check: yes

- name: start kubelet service
  service:
    name: kubelet
    state: started
    enabled: yes
