---
# tasks file for ssh_key
- name: install sshpass
  yum:
    name: sshpass
    state: present

- name: delete ssh key
  file:
    path: ~/.ssh
    state: absent
  when: delete_ssh_dir == 1

- name: check ~/.ssh
  shell: ls ~/.ssh | wc -l
  register: ssh_exist
  
- name: print check ~/.ssh result
  debug: 
    var: ssh_exist

- name: generate ssh key
  shell: ssh-keygen -t rsa -N '' -f ~/.ssh/id_rsa
  when: ssh_exist.stdout|int == 0

- name: ssh-copy-id
  shell: sshpass  -p "{{ ansible_master_ssh_pass }}" ssh-copy-id  "{{ ansible_master }}" -o stricthostkeychecking=no

- name: copy authorized_key
  authorized_key:
    user: "{{ ansible_ssh_name }}"
    state: present
    key: "{{ lookup('file', '~/.ssh/authorized_keys') }}"
